### ISSUE TITLE
Improve usability of Doxygen API documentation

### ISSUE THREAD

**Issue by mhthies** [modm-io/modm#100]
- [ ] Document modm:docs module in module.md
- [x] Add lbuild option to enable Doxygen HTML generation and disable Markdown generation
- [x] Generate doxygen \ingroup tags from lbuild module name to create a coherent structure of doxygen
- [x] Refer to modm:docs module at https://modm.io/guide/getting-started/#discovering-modm

**Comment by salkinium** [comment]
I also added a README to the example folder with usage instructions.
