### ISSUE TITLE
Resumable functions don't compile with gcc13

### ISSUE THREAD

**Issue by hshose** [modm-io/modm#1012]
When I compile protothreaded code with my gcc 13

e.g., the `examples/nucleo_g474re/max31855/`, I get the following error without any further hints from the compiler:

```
main.cpp: In member function 'bool ThermocoupleThread::run()':
modm/src/modm/processing/protothread/macros.hpp:91:22: error: jump to case label
   91 |                 case __LINE__: \
      |                      ^~~~~~~~
```

My gcc is `arm-none-eabi-gcc --version`: `arm-none-eabi-gcc (Arch Repository) 13.1.0`

**Comment by salkinium** [comment]
Well… it is undefined behavior. Just in time to switch to fibers with #1001! (no seriously, we're switching to fibers, I'm tired of this bullshit).
