### ISSUE TITLE
No module named 'modm.parser' 

### ISSUE THREAD

**Issue by rleh** [modm-io/modm#111]
```
lbuild build
No module named 'modm.parser' 

You might be missing the git submodules in `ext/`.
Try:
    cd modm
    git submodule update --init
then build again.
```

**Comment by rleh** [comment]
@salkinium

**Comment by rleh** [comment]
```
$ cd modm/
$ git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
```

**Comment by salkinium** [comment]
Did you by any chance do `pip3 install modm`? Cos modm-devices is conflicting with that, and it sucks.

**Comment by rleh** [comment]
Hmm, `pip3 uninstall modm` fixes this problem

**Comment by salkinium** [comment]
This is a legacy bug in modm-devices, because the parser is in `ext/modm-devices/tools/device/modm/` and thus is shadowed by the global modm module.
I'll rename this folder to `modm_devices` and adapt the DFG code.
