### ISSUE TITLE
support L443CCT6

### ISSUE THREAD

**Issue by L928** [modm-io/modm#112]
I would like to have L443CCT6 supprted.
Maybe I can help ... but need some assitance where to start.

**Comment by salkinium** [comment]
The STM32L443CCT target is already supported (all L4* are) and [compiles successfully on our CI](
https://6913-77459564-gh.circle-artifacts.com/0/log/stm32l443cct.log).
You can `lbuild discover -n ":target"` to get the full list of supported devices.

Did you mean you want a board support package for a Nucleo board with that target? If I’m not mistaken, there is [only a Nucleo board with the L433rc](
https://www.st.com/en/evaluation-tools/stm32-mcu-nucleo.html), not the L443cc.

**Comment by rleh** [comment]
There is a project ([micro-motor](https://github.com/roboterclubaachen/micro-motor)) using the STM32L433CCU controller: https://github.com/roboterclubaachen/micro-motor/blob/a5fb5d4a0be56cdeb28e75a846eb2528ff5fc529/src/test_blink/project.xml#L13

**Comment by salkinium** [comment]
I'm closing this since the target should work:

```xml
<option name=":target">stm32l443cct</option>
```

Feel free to reopen if you have further issues.
