### ISSUE TITLE
CI Failling in a apprently nor related point 

### ISSUE THREAD

**Issue by victorandrehc** [modm-io/modm#1131]
Hello there,
I opened a PR fixing a path inclusion on the dac for the STM32, Unexpectedly I am receiving an error on modm CI for the macOs testing. Can someone help me decipher why this error is happening?
![image](https://github.com/modm-io/modm/assets/10964478/0a2ff6b0-6144-40b1-92a7-256e50cffc4c)

**Comment by salkinium** [comment]
It's fine if you just use the PR to point out the issue, no need to open a separate issue.

**Comment by chris-durand** [comment]
It's [a bug in Apple's linker](https://forums.developer.apple.com/forums/thread/737707) shipped with Xcode tools prior to version 15.1. I've pushed a commit onto #1129 that should resolve the issue by updating the CI environment.
