### ISSUE TITLE
Uart read (buffer) function should return number of bytes read so far.

### ISSUE THREAD

**Issue by ku3i** [modm-io/modm#114]
https://github.com/modm-io/modm/blob/4e1d7dc8489f9d689555d90ed1ac92d258e89b4c/src/modm/platform/uart/at90_tiny_mega/uart_rx.cpp.in#L88

The header file https://github.com/modm-io/modm/blob/4e1d7dc8489f9d689555d90ed1ac92d258e89b4c/src/modm/architecture/interface/uart.hpp#L160
states: 

> Number of bytes which could be read, maximal `length`

imho, it should return "i" here, which is the number of bytes which were actually read so far.

**Comment by salkinium** [comment]
Yes, this seems to be a bug, the [STM32 UART also returns `i` here](
https://github.com/modm-io/modm/blob/develop/src/modm/platform/uart/stm32/uart.cpp.in). Do you want to fix this with a PR?
