### ISSUE TITLE
STM32C011F6P6

### ISSUE THREAD

**Issue by Apehaenger** [modm-io/modm#1186]
Just started with this interesting HAL approach but unfortunately stumble in the beginning.

Tried to get it running for a custom PCB with a STM32C011F6P6.

For sure I saw at the [main page](https://github.com/modm-io/modm#microcontrollers) that's not officially supported yet, but found it listed in the https://github.com/modm-io/modm-devices repository.

When I try `<option name="modm:target">stm32c011f6p6</option>` I get an "Target is unknown".

Stupid newbie failure or does someone has a hint what to do?

**Comment by salkinium** [comment]
Try enabling it here: 
https://github.com/modm-io/modm/blob/develop/repo.lb#L86

There will probably be a bunch of failures in lbuild, try to hack it and open a PR which I can then collaborate on.
