### ISSUE TITLE
this_fiber::poll() condition polarity inconsistent

### ISSUE THREAD

**Issue by WasabiFan** [modm-io/modm#1227]
Regarding the implementation of `this_fiber::poll()`:

https://github.com/modm-io/modm/blob/7b571a67ac525addbe6698f1b15963d4af0563a3/src/modm/processing/fiber/functions.hpp#L56-L65

My reading of the implementation is that it will block while the condition returns false. However, the docstring says it blocks while the condition returns true.

This also indicates that the following usages are incorrect:
1. The fiber tests use trivial "return true" conditions which I believe are intended to block indefinitely but actually return immediately. Although, I don't really understand what these tests are intended to do. They aren't actually running in a fiber as far as I can tell. https://github.com/modm-io/modm/blob/7b571a67ac525addbe6698f1b15963d4af0563a3/test/modm/processing/fiber/fiber_test.cpp#L104-L120
2. The `Timeout::wait` function returns immediately. https://github.com/modm-io/modm/blob/7b571a67ac525addbe6698f1b15963d4af0563a3/src/modm/processing/timer/timeout_impl.hpp#L129-L134

I did a grep for `this_fiber::poll` and inspected each call site in the repo to convince myself that they're correct. I _believe_ these are the only two buggy ones.

I'm not sure if the desired change is to update the documentation and two mentioned call sites or change the function behavior, so just posting an issue for now.

**Comment by salkinium** [comment]
1. Yes, the doc string is wrong, should be `/// Yields the current fiber while bool condition() returns false.`
2. The unit test is correct, it tests immediate return, ie. without any call to `yield()` outside of a fiber context.
3. That's wrong it should be `modm::this_fiber::poll([this]{ return execute(); });`. The periodic timer has it correct though.
