### ISSUE TITLE
[stm32] `SCB_InvalidateDCache()` might crash on startup

### ISSUE THREAD

**Issue by jgmess-dlr** [modm-io/modm#1235]
In case the DCache was already enabled before startup, for instance because the application is not starting from the internal STM bootloader but something like u-boot, that already uses the cache, a simple `SCB_InvalidateDCache()` might cause the application to crash.
Instead, a call to 'SCB_CleanInvalidateDCache()' mitigates the problem and has the same overall effect.

**Comment by salkinium** [comment]
Sure, wanna make a PR? This will probably also apply to the I-Cache then.
