### ISSUE TITLE
Change: "nrf24hal" to "nrf24phy" in nrf24-scanner example

### ISSUE THREAD

**Issue by FadiBunni** [modm-io/modm#143]
The nrf24-scanner example, has "nrf24hal" as a function to be called, but it does not exists. It should be changed to "nrf24phy"

**Comment by salkinium** [comment]
Can you point me to [the line in question in the example code?](https://github.com/modm-io/modm/blob/develop/examples/stm32f4_discovery/radio/nrf24-scanner/main.cpp).

`nrf24hal` is not a function, but a type if I'm not mistaken.
```cpp
typedef modm::Nrf24Phy<SpiMaster2, Csn, Ce> nrf24hal;
```

**Comment by salkinium** [comment]
Oh I see, the naming of the type should be `nrf24phy`. cc @daniel-k

**Comment by FadiBunni** [comment]
All places where it says nrf24hal::xxxxxxx has to be changted to nrf24phy::xxxxxx. My program cannot find nrf24hal, but reading into the code I found out that you must have changed it to nrf24phy.

**Comment by salkinium** [comment]
Do you @FadiBunni want to open a Pull Request with that change? It's a good first issue to take you through the process.

**Comment by FadiBunni** [comment]
Yes 👍

**Comment by FadiBunni** [comment]
I never done it before, but would like to know how.

**Comment by salkinium** [comment]
> I never done it before, but would like to know how.

Possibly the easiest way is to do it online:
https://help.github.com/articles/editing-files-in-another-user-s-repository/

Here is the [file in edit mode](https://github.com/modm-io/modm/edit/develop/examples/stm32f4_discovery/radio/nrf24-scanner/main.cpp) to get you started.

**Comment by salkinium** [comment]
For more complicated changes, you should commit your changes to a separate branch on your fork and manually open the PR:
https://help.github.com/articles/creating-a-pull-request/

**Comment by FadiBunni** [comment]
Alright, I made the simple change for now, but will use the guide for complicated changes, when there is more stuff. 

ps: I sent you a mail :)

**Comment by salkinium** [comment]
Do you want to open a PR with your changes? 
https://github.com/FadiBunni/modm/commit/ec0c030e91817edf9da38c3d96b340c7abcdd051

**Comment by salkinium** [comment]
Fixed in #149
