### ISSUE TITLE
Mismatched declaration and implementation of _delay_ms/us/ns on cortex

### ISSUE THREAD

**Issue by fb39ca4** [modm-io/modm#156]
In src/modm/platform/clock/cortex/delay.hpp, these functions are declared as accepting uint32_t arguments, but the implementation in delay.cpp uses uint16_t. I noticed this when I enabled link-time-optimization and GCC warned it might not produce correct code. Was there a reason behind this or can it be changed?

**Comment by salkinium** [comment]
No, that‘s a bug, everything uses `uint16_t`, so should these declarations. You want to open a PR?
https://github.com/modm-io/modm/blob/develop/src/modm/platform/clock/cortex/delay.hpp#L23-L25

Please be aware that LTO breaks our custom linker scripts, that‘s why it‘s not enabled by default. But maybe there‘s been a fix in the last year?
https://mobile.twitter.com/salkinium/status/959488890133450752
