### ISSUE TITLE
Compiling examples on Windows causes multiprocessing infinite recursion

### ISSUE THREAD

**Issue by operativeF** [modm-io/modm#164]
There's no python os.fork on Windows, so infinite recursion occurs when executing the script examples_compile.py. I added a guard for this in a branch I made, but I'm not sure of what the consequences are on other OSes. My branch is here: https://github.com/operativeF/modm/tree/fix/win_multiprocessing
but again, I'm not familiar enough with python or other OSes to give a better idea outside of this quick fix.

**Comment by salkinium** [comment]
I’ll test this, pretty sure this is the right thing to do not just for Windows.
