### ISSUE TITLE
Reproducible library generation

### ISSUE THREAD

**Issue by strongly-typed** [modm-io/modm#20]
I'd like to check in the generated library to my project to freeze the state and reduce external utility dependencies on building the project.
Of course, the library configuration shall be part of the repository and can be regenerated at any time.

I noticed that a second run of `lbuild build` does not generate the identical library.

```diff
diff --git a/src/modm/src/modm/platform/gpio/gpio_A0.hpp b/src/modm/src/modm/platform/gpio/gpio_A0.hpp
index 18035a0..1591a88 100644
--- a/src/modm/src/modm/platform/gpio/gpio_A0.hpp
+++ b/src/modm/src/modm/platform/gpio/gpio_A0.hpp
@@ -223,10 +223,11 @@ public:
                        "GpioA0::Ch1 only connects to Tim2!");
        };
        template< Peripheral peripheral >
-       struct Etr { static void connect();
+       struct In0 { static void connect();
                static_assert(
-                       (peripheral == Peripheral::Tim2),
-                       "GpioA0::Etr only connects to Tim2!");
+                       (peripheral == Peripheral::Adc1) ||
+                       (peripheral == Peripheral::Adc2),
+                       "GpioA0::In0 only connects to Adc1 or Adc2!");
        };
        template< Peripheral peripheral >
        struct Wkup { static void connect();
@@ -235,11 +236,10 @@ public:
                        "GpioA0::Wkup only connects to Sys!");
        };
        template< Peripheral peripheral >
-       struct In0 { static void connect();
+       struct Etr { static void connect();
                static_assert(
-                       (peripheral == Peripheral::Adc1) ||
-                       (peripheral == Peripheral::Adc2),
-                       "GpioA0::In0 only connects to Adc1 or Adc2!");
+                       (peripheral == Peripheral::Tim2),
+                       "GpioA0::Etr only connects to Tim2!");
        };
 };
```

This makes it difficult to track changes in the generated code.

Would it be possible to make sure the output is reproducible, e.g. by sorting items alphabetically?

**Comment by salkinium** [comment]
> Would it be possible to make sure the output is reproducible, e.g. by sorting items alphabetically?

Yes, fixed in develop.
However, this should be part of the CI, otherwise I there is no chance to detect this, especially since the examples all gitignore the output. This would probably be done in the generic example folder, which should also be compiled for all boards.

**Comment by strongly-typed** [comment]
For the last couple of weeks this has been stable. Updating modm created the same output on the files that did not change. So I consider this as closed for now. Thanks for fixing!
