### ISSUE TITLE
UART RX interrupt name not correct for ATmega8

### ISSUE THREAD

**Issue by Sh4rK** [modm-io/modm#211]
Hi again!

A problem has come up with the UART on ATmega8. [The UART template](https://github.com/modm-io/modm/blob/66c0868dcf8a4b05105ebffacb9acc63af6ecbac/src/modm/platform/uart/at90_tiny_mega/uart_rx.cpp.in#L32) assumes that the RX interrupt name is `USART{{ id }}_RX`, but on the mega8 it is `USART_RXC`.

According to the [avr-libc docs on interrupts](https://www.nongnu.org/avr-libc/user-manual/group__avr__interrupts.html) the devices that use this interrupt name are ATmega16, ATmega32, ATmega323, ATmega8.

What's the correct way to fix this?

**Comment by salkinium** [comment]
We use an unhealthy dose of preprocessor for that, because this is an insane problem:
https://github.com/modm-io/modm/blob/66c0868dcf8a4b05105ebffacb9acc63af6ecbac/src/modm/platform/uart/at90_tiny_mega/uart_defines.h#L89

This is missing the “no instance” case that you just added.
