### ISSUE TITLE
LPC memory layout / Shared RAM with on-chip API

### ISSUE THREAD

**Issue by strongly-typed** [modm-io/modm#221]
In

https://github.com/modm-io/modm/blob/develop/tools/devices/lpc/lpc11c24.xml#L18
```xml
<driver name="core" type="cortex">
      <memory name="sram1" access="rwx" start="0x10000100" size="8"/>
```
the start of the RAM was assigned to to `0x1000 0100` with a size of 8 KiBytes.

Accordingly to Figure 6 in [UM10398.pdf](https://www.nxp.com/docs/en/user-guide/UM10398.pdf), RAM starts at `0x1000 0000`

<img width="369" alt="image" src="https://user-images.githubusercontent.com/1626990/58710537-cee95800-83bc-11e9-8ecb-9dc0cca8fd01.png">

Additionally, accordingly to section 17.4.1 ("Calling the C_CAN API"), "On-chip RAM from address 0x1000 0050 to 0x1000 00B8 is used by the CAN API.":

<img width="619" alt="image" src="https://user-images.githubusercontent.com/1626990/58710632-0f48d600-83bd-11e9-9043-9270c0f361d6.png">

This might be the reason why the first used RAM was moved to `0x1000 0100` in xpcc back then.

I just want to clarify this to do the right things in the future. We probably need a feature in modm to reserve some RAM block for the use of on-chip peripherals / API code?!

**Comment by salkinium** [comment]
> We probably need a feature in modm to reserve some RAM block for the use of on-chip peripherals / API code?!

That would be done with the linkerscript of the port, so modm already supports that. The device file should be as accurate to the hardware as possible with all interpretation being done in modm. So that start address should be fixed.

**Comment by strongly-typed** [comment]
I will fix this in my modm port of LPC11C24.
How would the linkerscript reserve this RAM space?

**Comment by salkinium** [comment]
I think the linkerscript would just start at 0x100 and ignore the first 256B. However you need to be careful about the vector table relocation which probably has an aligment requirement higher than that.

**Comment by salkinium** [comment]
Oh, but this is a Cortex-M0, so there is no VTOR relocation anyways.

**Comment by salkinium** [comment]
I'm closing this, since LPC is not supported by modm and probably won't be in the future either.
