### ISSUE TITLE
Bluepill cannot be programmed with stlink v2.1

### ISSUE THREAD

**Issue by asmfreak** [modm-io/modm#234]
The config, generated for bluepill specifies v2, which, for some very bizarre reason, worked on Windows with stlink v2.1.
It didn't work on Linux though.

**Comment by salkinium** [comment]
Should we change the config, or should we remove the config.
https://github.com/modm-io/modm/blob/develop/tools/openocd/modm/stm32f103_blue_pill.cfg#L3

**Comment by asmfreak** [comment]
I think we should change the config and let users decide
