### ISSUE TITLE
Add an option to bring more scons tools on per-project basis

### ISSUE THREAD

**Issue by asmfreak** [modm-io/modm#292]
Adding this will help straighten the process of adding more scons tools from external projects. It'll help fix, for example, #220. 

* Paths should be specified as pairs input and output paths (I'm not sure, how lbuild can handle such contruct). 
* Additional tools will be specified either by name only (then it'll be searched in all paths specified above) or by it's relative-to-project or full path. If specified by full path, they should be outputted in the default `modm/scons/site-tools` path.

**Comment by salkinium** [comment]
Adding the tool is not enough, you also need to construct it and give it an alias. I think this is were you need to build your own custom SConstruct file, based off the one in modm.

**Comment by asmfreak** [comment]
Welp. I really thought that this could push #220 to be resolved.

**Comment by salkinium** [comment]
You should be able to commit the SCons tool to your repository in a separate folder (not in the generate path) and then add this to the SConstruct (after the SConscripts were called):

```py
env.Append(toolpath=[
    abspath("path/to/folder"),
])
env.Tool("compilation_db")
env.Alias("comp_db", env.CompilationDatabase('compile_commands.json'))
```

Make sure to disable the `modm:build:scons:include_sconstruct` option.

**Comment by salkinium** [comment]
I think a better solution was found with #293. I don't intend to add this functionality, since a custom SConstruct is the way to go here.
