### ISSUE TITLE
STM32F303x8 USART1 clock defaults to PCLK1

### ISSUE THREAD

**Issue by mikewolfram** [modm-io/modm#298]
The clock for the USART1 on the Nucleo-F303K8 board defaults to PCLK1, which is divided by 2. The line

` static constexpr uint32_t Usart1 = Apb2;`

must be changed to

` static constexpr uint32_t Usart1 = Apb1;`

The reference manual tells it's connected to APB2, but the clock configuration register CFGR3 sets it to PCLK1 per default. See pages 162ff.

![Screen Shot 2019-10-02 at 8 57 05 AM](https://user-images.githubusercontent.com/56061555/66024171-6d183680-e4f3-11e9-8214-c0ad70550b62.png)

**Comment by salkinium** [comment]
😱🥴

The board files are written by hand, which makes them error prone like this. It's on my long TODO list to automate this away.

Do you want to open a quick PR for this issue (and maybe check the remaining clocks too)?

**Comment by mikewolfram** [comment]
Will look into it when I return from vacation.

**Comment by mikewolfram** [comment]
Looking through the docs again I found out, that I2C1 default clock is HSI (8 MHz). I'll create a PR.
