### ISSUE TITLE
Non-escaped backslashes in SConstruct file on Windows

### ISSUE THREAD

**Issue by WasabiFan** [modm-io/modm#299]
Backslashes on Windows aren't escaped or translated; this may cause issues depending on your project name.

https://github.com/modm-io/modm/blob/5afe95ad8ab24f1e6b0324c1b4056451693febd5/tools/build_script_generator/scons/resources/SConstruct.in#L16

**Comment by salkinium** [comment]
Use jinja filter `modm.windowsify` for escaping paths correctly. See https://github.com/modm-io/modm/pull/204#discussion_r281034314.
