### ISSUE TITLE
Documentation: Highlight lbuild module names

### ISSUE THREAD

**Issue by rleh** [modm-io/modm#312]
The module names (for project.xml) should be mentioned in the module documentation (https://modm.io) and in the Doxygen/Doxypress documents (https://docs.modm.io/).

**Comment by salkinium** [comment]
Currently the module name is part of the title for the module docs, but not the API docs.
![IMG_0400](https://user-images.githubusercontent.com/163066/68087870-e213be80-fe59-11e9-81bc-4663f9a897c5.jpg)

For Doxygen the module name is already encoded into the options, so it should be made explicit anyways.
![IMG_0401](https://user-images.githubusercontent.com/163066/68087871-e5a74580-fe59-11e9-946a-93adb5316258.jpg)

How would you like to see the module name be emphasized?

**Comment by rleh** [comment]
If someone doesn't know what the module name looks like, it's hard to guess that this strange beginning in the title is the module name.

I would suggest to add a line below the title like for the #include-file:

*Module name: `modm:ui:led`*

**Comment by salkinium** [comment]
Ok, agreed. 

What about: `<module>modm:ui:led</module>` ?

**Comment by rleh** [comment]
Exaktly :+1: 
I think the monospace/code-like formatting is important.

**Comment by rleh** [comment]
Something similar would be nice inside doxygen API docs.
I guess this has to be added here:
https://github.com/modm-io/modm/blob/3eb25dbb18fc88328bf0e243ed352de774316135/tools/doc_generator/group.dox.in#L7-L9
