### ISSUE TITLE
Support for RTC

### ISSUE THREAD

**Issue by dirkbr** [modm-io/modm#315]
It would be nice to have support for the internal RTC of the STM32F103 series.

**Comment by salkinium** [comment]
What features would the implementation require? What is your use-case for using the RTC?

**Comment by salkinium** [comment]
Ideally the API would implement the libc and libc++ interfaces for time and date, right? So the interface is kinda already defined, which is nice.

**Comment by dirkbr** [comment]
A libc and libc++ API would be perfect! One use-case is a mobile data logger, that doesn't have a permanent power supply.

**Comment by salkinium** [comment]
Note that modm is not designed for doing anything fancy with power (neither sleeping,  nor purely interrupt based operations, nor non-volatile storage, nor partial power operations), so check if you can meet your power budget *before* relying on modm too much.
