### ISSUE TITLE
STM32 ADC channels >= 10 broken

### ISSUE THREAD

**Issue by mikewolfram** [modm-io/modm#316]
Commit 086581565e088c4fda60e8d13a8a8b1fc9f0912b (adding support for L1) breaks ADC channels >= 10. A change in *src/modm/platform/gpio/stm32/pin.hpp.in* sets the ADC channel to always 1 when the Signal is `In10...In15`. Before supplying a fix I wanted to ask if this change has a purpose:

```diff
- Gpio{{ port ~ pin }}::AdcChannel<Peripheral::{{ signal.driver }}> = {{ signal.name.replace("In", "") }};
+ Gpio{{ port ~ pin }}::AdcChannel<Peripheral::{{ signal.driver }}> = {{ signal.name.replace("In", "")[0] }};
```

**Comment by salkinium** [comment]
Ah, dang. I wanted to filter out only the number, without any suffix.
https://github.com/modm-io/modm-devices/blob/develop/devices/stm32/stm32l1-51_52_62-c_d_e.xml#L498

This should be done in Python via a custom Jinja filter.

**Comment by salkinium** [comment]
Maybe something as simple as `"".join(filter(str.isdigit, name))` as a filter would be enough.

**Comment by mikewolfram** [comment]
Not sure whether I understand... Use it in the pin.hpp.in or module.lb file?

**Comment by salkinium** [comment]
Both ;-P

You'd define the filter in [the `module.lb` here](https://github.com/modm-io/modm/blob/develop/src/modm/platform/gpio/stm32/module.lb#L263):
```py
        def name2adc(name):
            return "".join(filter(str.isdigit, name))
        env.template(gpio_source, header_name, filter={"to_adc_channel": name2adc})
```

Then use this filter in the Jinja template:
```
Gpio{{ port ~ pin }}::AdcChannel<Peripheral::{{ signal.driver }}> = {{ signal.name | to_adc_channel }};
```

**Comment by salkinium** [comment]
You can even use an inline Python lambda function instead of the lame `name2adc`.
