### ISSUE TITLE
ST7565 display: "initialize" never called?

### ISSUE THREAD

**Issue by WasabiFan** [modm-io/modm#327]
I was referencing the ST7565 implementation when writing my own display controller driver. It appears that the protected `initialize` method isn't ever called by a parent class, and can never be called by an external user since it's `protected`. What am I missing here?

https://github.com/modm-io/modm/blob/develop/src/modm/driver/display/st7565.hpp#L51

**Comment by salkinium** [comment]
The driver is just really, really old and has probably just not been ported correctly by me. I think this is just a bug.

**Comment by salkinium** [comment]
Has your question been answered?

**Comment by WasabiFan** [comment]
I think we agree this is a bug, so in some sense "yes", but I'd still consider this an open bug.

**Comment by salkinium** [comment]
Yeah, sorry, I meant to say "Did you find a solution for this issue?"…

**Comment by WasabiFan** [comment]
:laughing: yeah, I was using this file as a reference so once I realized why the initialize method wasn't being called I made it public and called it from my system initialization function. So my situation is solved now. Thanks!
