### ISSUE TITLE
STM32L4 I2C NACK should be handled by I2C_EV

### ISSUE THREAD

**Issue by mikewolfram** [modm-io/modm#328]
Current implementation is handling the NACK in the error interrupt, but in reality it is an event and should therefor be handled there:

![image](https://user-images.githubusercontent.com/56061555/75043656-b841de80-54c0-11ea-9351-723fa653cd4f.png)

I made a quick a dirty fix and copied the part from the I2C_ERR handler to I2C_EV handler right after checking for stop. Works now.
Since I'm not an I2C expert maybe you could tell me, if that's the right position and especially if that needs to be handled in the template file to change it for L4 only? With some advice I'll provide a fix.

**Comment by salkinium** [comment]
Related to this https://github.com/modm-io/modm/pull/305. cc @nesos

**Comment by salkinium** [comment]
The L4 template is the place to fix it, yes.

**Comment by mikewolfram** [comment]
I had a look into #305 before. That one simply enables the NACK IRQ. On systems which use a global I2C interrupt handler this works fine. But if there are I2C_ERR and I2C_EV IRQ handlers this would simply not handle the NACK flag.

Looked into few reference manuals which I had on my disk. F3, F4, G4, L4 and F7 all tell, NACK is a I2C event. Still not clear to me is, which MCU have the global IRQ handler and which not. Beside the table in the first post some manuals use this graph:
![image](https://user-images.githubusercontent.com/56061555/75110698-a92e6e00-5631-11ea-9529-20dd7bfd3cb2.png)
Reading the table above could also mean, there are event and error interrupts as well as a global interrupt.

Anyway it looks to me the right place to handle NACK is the event IRQ handler. I'll prepare a PR and we can discuss whether the code is in the right place and does the right thing.
