### ISSUE TITLE
Timer broken on hosted

### ISSUE THREAD

**Issue by strongly-typed** [modm-io/modm#387]
Consider this example on hosted/macOS:

```
#include <modm/debug/logger.hpp>
#include <modm/processing/timer.hpp>

using namespace std::chrono_literals;

modm::ShortTimeout timeout;

int
main()
{
	int ctr(0);
	timeout.restart(500ms);

	while(true)
	{
		if (timeout.isExpired()) {
			MODM_LOG_DEBUG << "ping " << ctr++ << modm::endl;
			timeout.restart(500ms);
		}
	}
}
```

It spit out numbers without delays.

[Some code](https://github.com/modm-io/modm/blob/develop/src/modm/platform/can/canusb/canusb_impl.hpp#L104) that deals with real world peripherals relies on that.

Probably related to #374. I'll do a bisect soon.

**Comment by strongly-typed** [comment]
Broke from commit f1021b0 to c63a5366e. I cannot compile the commits in between.
Same behavior observed on macOS and in a docker container with Debian.

**Comment by salkinium** [comment]
Maybe the cast from int64_t to uint32_t is not the best idea… I didn't even test this \*shame\*.

**Comment by salkinium** [comment]
(can reproduce)

**Comment by salkinium** [comment]
hm, it works with a `modm::Timeout` instead of a ShortTimeout, so I suspect issues with casting from uint32_t to uint16_t ms.

**Comment by salkinium** [comment]
Yep, found the bug. I need to add some tests for this though…
