### ISSUE TITLE
ITM documentation outdated

### ISSUE THREAD

**Issue by hshose** [modm-io/modm#419]
Currently, ITM documentation at [1] uses `scons itm` as programming command, which does not work. Documentation at [2] is correctly stating `scons log-itm` for the convenience function

Example for manual openocd call is also outdated in [1], here `modm_log_itm` should be `modm_itm_log` in command: 
`openocd -f "modm/openocd.cfg" -c "modm_itm_log itm.fifo 168000000"` as example for manually calling openocd, 

[1] https://modm.io/reference/module/modm-platform-itm/
[2] https://modm.io/reference/module/modm-build-scons/

**Comment by salkinium** [comment]
Ooops, I forgot this when I refactored the tooling.

Please open a PR to fix it, you basically already written a patch and you can do it online.
