### ISSUE TITLE
DMA support

### ISSUE THREAD

**Issue by ghost** [modm-io/modm#423]
I need DMA support to a w5500 SPI ethernet module on a stm32f411. Is anyone working on such solution or do i start from scratch, i probably break or extend the SPI api anyway since i need a more async friendly interface.

**Comment by salkinium** [comment]
DMA for SPI was implemented for STM32L4 in #400. You will have to adapt the DMA API from #371 using the modm-devices data for the STM32F4.

Feel free to change the SPI interface to your needs, I'm interested in more use-cases to distill into a potential new API.
