### ISSUE TITLE
Tags and Releases are missing.

### ISSUE THREAD

**Issue by strongly-typed** [modm-io/modm#44]
[Some](https://github.com/modm-io/modm/commit/c442b5ce1fc4630a37f2b3bf7e126ead8091f816) commits are marked as releases, although no Github [Releases](https://github.com/modm-io/modm/releases) and not [tags](https://github.com/modm-io/modm/tags) are defined.

**Comment by salkinium** [comment]
Those commits come from merging the xpcc history into modm. 

I only planning to do modm releases and changelog with 2018q4, when xpcc with be archived. It's unclear to me how to "merge" the changelogs/releases of xpcc into modm, so I just procrastinate this problem into the future. 😜
