### ISSUE TITLE
Python fails to parse number during lbuild run

### ISSUE THREAD

**Issue by mikewolfram** [modm-io/modm#450]
In modm/src/modm/platform/clock/rcc.cpp.in is this line:
```cpp
uint32_t modm_fastdata fcpu({{ "{0:,}".format((1e6 * hsi_frequency)|int).replace(',', "'") }});
```
Running lbuild causes a template error. When I replace 1e6 with 1000000 then it runs without complains.

Is it a problem of my Python? I'm running Python 3.7.4 on macOS X 10.14.x (Mojave).

**Comment by salkinium** [comment]
This seems to be an issue with Jinja2 in *some* circumstances that I couldn't investigate. It seems like changing this to `1000000` is a good solution.
