### ISSUE TITLE
SysTick on SAM has wrong scaling

### ISSUE THREAD

**Issue by henrikssn** [modm-io/modm#459]
Just for tracking: Seems like timers are 8x off on SAM due to the CPU not implementing reference clock (see errata).

We therefore need to turn of the prescaler always on SAM.

**Comment by salkinium** [comment]
Is this an ARM Errata inside the Cortex-M core? Could you link to the errata sheet?

The fractional division algo from #217 may not work without the /8 prescaler, so that would be an issue…

**Comment by henrikssn** [comment]
> Current SAM D21 errata indicate that the Reference Clock is un-implemented and that the user should configure the SysTick clock source to be the CPU Clock (CLKSOURCE==1).

https://microchipdeveloper.com/32arm:samd21-systick
