### ISSUE TITLE
Ili9341 SPI not compiling

### ISSUE THREAD

**Issue by mikewolfram** [modm-io/modm#483]
The Ili9341 doesn't compile for me anymore when using with SPI interface. In extension to my implementation #464 the code in the #437 adds a parallel interface. But the templated constructor prevents from compiling. Also for SPI it expects an argument to the constructor.

Maybe you could have a look into it?

**Comment by salkinium** [comment]
cc @ASMfreaK

**Comment by asmfreak** [comment]
I'll look into it today.

**Comment by asmfreak** [comment]
It seems, that I've made a mistake in `std::enable_if`.

**Comment by rleh** [comment]
It would be nice to have examples for Ili9341 both with SPI and parallel mode. Thus the error would be noticeable in the CI in the future.

**Comment by asmfreak** [comment]
Yeah. That were my thought exactly yesterday. I've created an example to. Will try to fix and add a new example.
