### ISSUE TITLE
Is there an example that show how to use STM32 usb device?

### ISSUE THREAD

**Issue by zhangzq71** [modm-io/modm#505]
I can't find any examples in modm examples dir that show how to use STM32 usb device, such as a CDC device.

**Comment by salkinium** [comment]
Here are a couple:

- Generic Example for STM32 and SAM devices: MSC, CDC, MIDI: https://github.com/modm-io/modm/tree/develop/examples/generic/usb
- FIrmware upgrade via MSC and FatFs: https://github.com/modm-io/modm/tree/develop/examples/stm32f411ceu_mini_f411/usbfatfs
- Firmware upgrade via DFU runtime: https://github.com/modm-io/modm/tree/develop/examples/stm32f3_discovery/usb_dfu

**Comment by salkinium** [comment]
The trick is to set the lbuild option `<option name="modm:tinyusb:config">device.cdc</option>` to generate the USB descriptors, and then use `modm::platform::UsbUart{#ITM}` as an IODevice.

```cpp
modm::IODeviceWrapper<modm::platform::UsbUart0, modm::IOBuffer::DiscardIfFull> usb_io_device0;
modm::IOStream usb_stream0(usb_io_device0);
```

**Comment by zhangzq71** [comment]
Thank you very much, let me try.

**Comment by salkinium** [comment]
I ran out of motivation for implementing more USB descriptors, so have a look at the TinyUSB examples as well, since modm only provides the platform port for the TinyUSB core code: https://github.com/hathach/tinyusb/tree/master/examples/device

**Comment by zhangzq71** [comment]
Thanks, I knew modm one day before and feel it is great and learning how to use it. And the usb function I need is the CDC ACM, and there is an example for it, that is enough.
