### ISSUE TITLE
Missing lbuild dependency in documentation

### ISSUE THREAD

**Issue by ceremcem** [modm-io/modm#541]
`lbuild` dependency is missing in [installation instructions](https://github.com/modm-io/modm/blob/1b8a53415cbb73db24037fa3ebc8d78125cd486b/docs/src/guide/installation.md#linux). As I'm not sure where to add `pip install lbuild` (or do you prefer `pipx` for this too?), I only create this issue (without creating a PR).

**Comment by rleh** [comment]
The `pip3 install modm` in the installation instructions will install the lbuild package as a dependency.

**Comment by ceremcem** [comment]
Ah, sorry, my mistake.
