### ISSUE TITLE
Environment Variable Parsing for xml file parsers

### ISSUE THREAD

**Issue by kikass13** [modm-io/modm#561]
What:
 * project.xml should have native absolute path support via env variables
 
How:
 * provide a filled environment dictionary to the parser before invoking it

**Comment by kikass13** [comment]
I did add that function to lbuild

https://github.com/kikass13/lbuild/commit/039c2282f2a9ed3b2f38a73d8f727dbf4ed91ee4

shall I create a merge request for that into lbuild?

**Comment by salkinium** [comment]
Yes, that looks very useful indeed!
