### ISSUE TITLE
Ethernet freertos_tcp on f439zi nucleo not working

### ISSUE THREAD

**Issue by kikass13** [modm-io/modm#583]
Hello,
I will append my experience here, even though there is an issue for that already:
 * https://github.com/modm-io/modm/issues/447

### Preamble
I got @mikewolfram 's `lan8720a` phy driver and the corresponding example (using freertos_tcp) working with the f767zi nucleo board after changing some of the PHY pins hardcoded in the example he gave. 

### Getting There
After that, I tried to get it running on the f439zi but was unable to do so. After some hours of experimenting with the freertos network scheduler (RTOS_IP) and ethernet stack, i finally ended inside the event loop (controlled by freertos ip stack) of the `lan8720a` ([see here](https://github.com/modm-io/modm/blob/develop/ext/aws/modm_lan8720a.cpp#L421)) which should eventually handle arp requests coming from another laptop connected to the board via ethernet. 

### The Problem
The [event loop](https://github.com/modm-io/modm/blob/develop/ext/aws/modm_lan8720a.cpp#L421) handles events constantly (as expected), but every event is regarded as a NOP `modm::platform::eth::Event::None` and therefore ignored. Which means that the feeding function, responsible for setting proper events, is not working properly. 

As it turns out, the producer function is [this](https://github.com/modm-io/modm/blob/develop/ext/aws/modm_lan8720a.cpp#L623-L650) ISR 
```cpp
MODM_ISR(ETH)
{
	using modm::platform::eth;
	using modm::ethernet;

	BaseType_t xHigherPriorityTaskWoken = pdFALSE;
	EMAC::InterruptFlags_t irq = EMAC::getInterruptFlags();
	EMAC::acknowledgeInterrupt(irq);

	if (irq & (eth::InterruptFlags::Receive | eth::InterruptFlags::ReceiveBufferUnavailable)) {
		ethernet::isrEvent |= eth::Event::Receive;
		if (ethernet::emacTaskHandle) {
			vTaskNotifyGiveFromISR(ethernet::emacTaskHandle, &xHigherPriorityTaskWoken);
			portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
		}
	}
	if (irq & (eth::InterruptFlags::Transmit)) {
		ethernet::isrEvent |= eth::Event::Transmit;
		if (ethernet::emacTaskHandle) {
			vTaskNotifyGiveFromISR(ethernet::emacTaskHandle, &xHigherPriorityTaskWoken);
			portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
		}
	}

	if (EMAC::getInterruptFlags() & eth::InterruptFlags::AbnormalIrqSummary) {
		// not used yet
	}
}
```

My test have shown (led blinky, event chain debugging) that this specific ISR is not called properly. 
Is there something you guys can tell me about the differences between the interrupt handling (mainly ethernet-DMA interrupts) ?

### Other Stuff

* I tried checking registers for interrupts, dma and others to see if any flags have changed but it seems that these chips(f4 & f7) are equal in that matter
* we have an internal issue where this errata was evaluated, but we could not find anything in particular which could be problematic: https://www.st.com/resource/en/errata_sheet/dm00068628-stm32f427437-and-stm32f429439-line-limitations-stmicroelectronics.pdf

### End

Thank you for reading, maybe someone can help

**Comment by salkinium** [comment]
Not a FreeRTOS expert, so I can only say some generic stuff:

- There's a minimum IRQ priority of I think 13 imposed by FreeRTOS, which uses lower priorities for SysTick and PendSV etc. Perhaps we're accidentally setting something wrong, or a lower prio interrupt is blocked by something higher?
- You can try `NVIC_SetPending(ETH_IRQn);` to test if the IRQ handler is even callable at all.
- There also a `ETH_WKUP` interrupt? Not sure what it does.
- Maybe there's some error state in the ethernet peripheral that's not being acknowledged, and therefore blocks new events? Maybe the `AbnormalIrqSummary` requires clearing some register in addition to the clearing flags.

**Comment by kikass13** [comment]
> Not a FreeRTOS expert, so I can only say some generic stuff:

its not a freertos problem, so your answers are helpful.
Im gonna try some of the things you mentioned and get back as soon as possible (could take some days)

**Comment by mikewolfram** [comment]
The ethernet implementation is an adaption of the code provided in FreeRTOS+TCP for STM32, which uses the STM32 HAL. There seem to be differences between F4 and F7 families. FreeRTOS+TCP includes a modified (hacked?) version of the HAL ETH files for both F4 and F7.

Since I only have access to F7 boards my focus was to get that one working first and asking for help to complete the F4 part. To get started I'd look into the STM32 HAL ETH files in original FreeRTOS+TCP and check for differences.

**Comment by kikass13** [comment]
@mikewolfram 
I am not familiar with cube and where their HAL examples are. Do you mean these (probably not?!): 
 * https://github.com/STMicroelectronics/STM32CubeF7/blob/master/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c
 * https://github.com/STMicroelectronics/STM32CubeF4/blob/master/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c

because as far as i can tell, these two are identical. Except for one simple function `static void ETH_Delay(uint32_t mdelay);` which is used for the f4

 * there is also a note on top of the f4 driver which says 
> The PTP protocol and the DMA descriptors ring mode are not supported in this driver

whatever that is worth

**Comment by mikewolfram** [comment]
It isn't in Cube nor their examples, it's in the FreeRTOS git:
https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/tree/main/portable/NetworkInterface/STM32Fxx

**Comment by kikass13** [comment]
Sorry i must misunderstood your reply then... 

I already looked a these in the past, but
i cant seem to understand where these files could differ except for the chip specific `_hal_eth.c` files

**Comment by mikewolfram** [comment]
You are right, there's only one source file but a few headers per chip.

As far as I remember they use quite a few macros, maybe they do something different?

**Comment by mikewolfram** [comment]
Another question, do you get the link-up event? IRQ aren't enabled before.

**Comment by kikass13** [comment]
> As far as I remember they use quite a few macros, maybe they do something different?

well i did a diff on the HAL_c files and the HAL_h files and they are essentially the same. And there are no further ifdefs in the freertos+tcp.c file you mentioned so i guess there's nothing more board specific?

**Comment by kikass13** [comment]
> Another question, do you get the link-up event? IRQ aren't enabled before.

as far as I remember (i did these test with gdb about two weeks ago) this code (https://github.com/modm-io/modm/blob/develop/ext/aws/modm_lan8720a.cpp#L374-L385) was called properly and the `autoNegotiationFailed` flag was false, which I figured means that configuration of the PHY was possible. 

## I can also confirm that 
 * the stack / driver runs normal and other freertos Tasks can run freely without problems.
 * the phy does something because i get a IFUP on my ethernet connection (using the other linux laptop) and the two leds blink whenever something happens on the ethernet rx/tx line
 * What happens is that `ARP` requests (and therefore ICMP packets) are not handled, which means that i do not receive the MAC address of the nucleo (ARP requests are normally handled by FreertosIP stack, but the driver does not forward anything so they never reach the stack).

**Comment by mikewolfram** [comment]
In the example is a hook `vApplicationIPNetworkEventHook`, which get's called, when the link is up and everything set up, so it should print the IP etc.

**Comment by kikass13** [comment]
Yes that part works.

**Comment by kikass13** [comment]
Yes that part works:
 
 * see my example https://github.com/kikass13/modm_ethernet/tree/f439zi_support (which is your example, but altered a bit )
 * and the output from the serial port

```
============================
Hello world ... 

Ethernet manager initializing ... 
Initialzing ethernet interface ...
Initializing scheduler
  -- Led blink task run()
  -- Network initialization task run()
  -- Http server task run()
   > IP address: 192.168.1.1
   > Netmask   : 255.255.255.0
   > Gateway   : 0.0.0.0
   > DNS       : 0.0.0.0
```

**Comment by rleh** [comment]
Maybe the updates FreeRTOS and FreeRTOS+TCP modules (#566) magically solve the problem? Could you test that @kikass13?

**Comment by kikass13** [comment]
@rleh 
I can do that, give me some days to do other stuff first :D

**Comment by jnewcomb** [comment]
I feel your pain..
It could be possible the ethernet DMA for the F4 if unable to operate in the 'modm_fastdata' section of memory.
In modm_lan8720a.cpp - edit this:

```
	modm_aligned(32) modm_fastdata
	static DmaDescriptor_t  DmaRxDescriptorTable[RX_BUFFER_NUMBER];

	/* Ethernet Tx DMA Descriptor */
	modm_aligned(32) modm_fastdata
	static DmaDescriptor_t  DmaTxDescriptorTable[TX_BUFFER_NUMBER];
```

to this
```
	modm_aligned(32)
	static DmaDescriptor_t  DmaRxDescriptorTable[RX_BUFFER_NUMBER];

	/* Ethernet Tx DMA Descriptor */
	modm_aligned(32)
	static DmaDescriptor_t  DmaTxDescriptorTable[TX_BUFFER_NUMBER];
```

Let me know if that fixes your issue..

**Comment by rleh** [comment]
The Ethernet MAC on STM32F4(29) is indeed not capable of accessing the DTC/CCM memory where the `modm_fastdata` should is located, while this access is possible on STM32F7.

![grafik](https://user-images.githubusercontent.com/2820734/114956788-e110fa00-9e5f-11eb-83fd-3ab38f3af75d.png)

![grafik](https://user-images.githubusercontent.com/2820734/114958117-afe5f900-9e62-11eb-87bb-e511e84ce2da.png)

---

I just removed the `modm_fastdata` attribute as suggested, but ethernet still does not work.
The data in `DmaTxDescriptorTable` is not actually the DMAed, but the data the pointers in `DmaTxDescriptorTable` point to is also somehow allocated (by FreeRTOS?) in the CCM memory. I disabled the whole CCM memory by modifying the linkerscript and now Ethernet works on my Nucleo-F429 board!

Thank you very much @jnewcomb!


<details>

<summary>Linkerscript</summary>

```linkerscript
/*
 * Copyright (c) 2011-2012, 2019, Fabian Greif
 * Copyright (c) 2012, 2015-2019, Niklas Hauser
 * Copyright (c) 2013, Sascha Schade
 * Copyright (c) 2013, 2015, Kevin Läufer
 *
 * This file is part of the modm project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 * ------------------------------------------------------------------------- */


MEMORY
{
	FLASH (rx) : ORIGIN = 0x08000000, LENGTH = 2097152
	CCM (rw) : ORIGIN = 0x10000000, LENGTH = 65536
	SRAM1 (rwx) : ORIGIN = 0x20000000, LENGTH = 114688
	SRAM2 (rwx) : ORIGIN = 0x2001C000, LENGTH = 16384
	SRAM3 (rwx) : ORIGIN = 0x20020000, LENGTH = 65536
	BACKUP (rwx) : ORIGIN = 0x40024000, LENGTH = 4096
	RAM (rwx) : ORIGIN = 0x20000000, LENGTH = 196608
    
}

OUTPUT_FORMAT("elf32-littlearm")
OUTPUT_ARCH(arm)

/* First executable instruction in an output file */
ENTRY(Reset_Handler)

/* the thread stack is used only for reporting hard fault conditions! It may therefore be small. */
PROCESS_STACK_SIZE  = 0;
/* the handler stack is used for main program as well as interrupts */
MAIN_STACK_SIZE     = 3072;
/* combined stack size */
TOTAL_STACK_SIZE = MAIN_STACK_SIZE + PROCESS_STACK_SIZE;



SECTIONS
{
	__rom_start = ORIGIN(FLASH);


	.vector_rom :
	{
		__vector_table_rom_start = .;
		__vector_table_ram_load = .;
		/* Initial stack address, Reset and NMI handler */
		KEEP(*(.vector_rom))
		. = ALIGN(4);
	} >FLASH


	.vector_ram (NOLOAD) :
	{
		__vector_table_ram_start = .;
		/* Vector table in RAM, only if remapped */
		KEEP(*(.vector_ram))
		. = ALIGN(4);
		__vector_table_ram_end = .;
	} >RAM


	.stack (NOLOAD) :
	{
		__stack_start = .;

		. += MAIN_STACK_SIZE;
		. = ALIGN(8);
		__main_stack_top = .;

		. += PROCESS_STACK_SIZE;
		. = ALIGN(8);
		__process_stack_top = .;

		__stack_end = .;
	} >RAM


	.fastdata : ALIGN(4)
	{
		__fastdata_load = LOADADDR(.fastdata);
		__fastdata_start = .;
		*(.fastdata)
		. = ALIGN(4);
		__fastdata_end = .;
	} >RAM AT >FLASH


	.heap0 (NOLOAD) :
	{
		*(.heap0)
		. = ALIGN(4);
		__heap0_start = .;
		. = ORIGIN(SRAM3) + LENGTH(SRAM3);
		__heap0_end = .;
	} >SRAM3


	.text : ALIGN(4)
	{
		*(.text .text.* .gnu.linkonce.t.*)
	} >FLASH

	.rodata : ALIGN(4)
	{
		*(.rodata .rodata.* .gnu.linkonce.r.*)
		KEEP(*(.init))

		. = ALIGN(4);
		__init_array_start = .;
		KEEP(*(SORT(.init_array.*)))
		KEEP(*(.init_array))
		__init_array_end = .;
	} >FLASH

	/* Unwind tables are used to unwind the stack for C++ exceptions. Even
	 * though we disabled exceptions, pre-compiled libraries such as libstdc++
	 * still have to raise exceptions. We still force discard all tables
	 * though and hook these exception throwers in code. */
	/DISCARD/ :
	{
		*(.ARM.extab* .gnu.linkonce.armextab.*)
		*(.ARM.exidx* .gnu.linkonce.armexidx.*)
		*(.eh_frame*)
	}
	/* Hardware init table */
	.hardware_init : ALIGN(4)
	{
		__hardware_init_start = .;
		/* Table symbols are alphabetically sorted! */
		KEEP(*(SORT(.hardware_init.order_*)))
		KEEP(*(SORT(.hardware_init)))
		__hardware_init_end = .;
	} >FLASH

	/* Assertion handler table */
	.assertion : ALIGN(4)
	{
		__assertion_table_start = .;
		KEEP(*(.assertion))
		__assertion_table_end = .;
	} >FLASH

	.build_id :
	{
		__build_id = .;
		KEEP(*(.note.gnu.build-id))
	} > FLASH


	.fastcode : ALIGN(4)
	{
		__fastcode_load = LOADADDR(.fastcode);
		__fastcode_start = .;
		*(.fastcode)
		. = ALIGN(4);
		__fastcode_end = .;
	} >FLASH


	/* initialized variables */
	.data : ALIGN(4)
	{
		__data_load = LOADADDR(.data);
		__data_start = .;
		*(.data .data.* .gnu.linkonce.d.*)
	} >RAM AT >FLASH

	/* code routines in RAM */
	.ramcode : ALIGN(4)
	{
		*(.ramcode .ramcode*)
		__data_end = .;
	} >RAM AT >FLASH

	/* uninitialized variables */
	.bss (NOLOAD) :
	{
		__bss_start = . ;
		*(.bss .bss.* .gnu.linkonce.b.*)
		. = ALIGN(4);
		__bss_end = .;
	} >RAM

	/* Global data not cleared after reset.  */
	.noinit (NOLOAD) :
	{
		__noinit_start = .;
		*(.noinit*)
		. = ALIGN(4);
		__noinit_end = .;
	} >RAM


	.heap1 (NOLOAD) :
	{
		*(.heap1)
		. = ALIGN(4);
		__heap1_start = .;
		. = ORIGIN(SRAM1) + LENGTH(SRAM1);
		__heap1_end = .;
	} >RAM


	.heap2 (NOLOAD) :
	{
		*(.heap2)
		. = ALIGN(4);
		__heap2_start = .;
		. = ORIGIN(SRAM2) + LENGTH(SRAM2);
		__heap2_end = .;
	} >RAM

	.heap3 (NOLOAD) :
	{
		*(.heap3)
		. = ALIGN(4);
		__heap3_start = .;
		. = ORIGIN(SRAM3) + LENGTH(SRAM3);
		__heap3_end = .;
	} >RAM

    

	/* TABLES! TABLES! ALL THE TABLES YOU COULD EVER WANT! TABLES! */
	.table.zero.intern : ALIGN(4)
	{
		__table_zero_intern_start = .;
		LONG(__bss_start)
		LONG(__bss_end)
		__table_zero_intern_end = .;
	} >FLASH


	.table.copy.intern : ALIGN(4)
	{
		__table_copy_intern_start = .;
		LONG(__data_load)
		LONG(__data_start)
		LONG(__data_end)
		LONG(__fastdata_load)
		LONG(__fastdata_start)
		LONG(__fastdata_end)
		__table_copy_intern_end = .;
	} >FLASH


	.table.zero.extern : ALIGN(4)
	{
		__table_zero_extern_start = .;
        
		__table_zero_extern_end = .;
	} >FLASH

	.table.copy.extern : ALIGN(4)
	{
		__table_copy_extern_start = .;
        
		__table_copy_extern_end = .;
	} >FLASH


	/* SRAM properties bit mask (16-bit):
	 *
	 * - 0x0001: accessible via S-Bus
	 * - 0x0002: accessible via D-Bus
	 * - 0x0004: accessible via I-Bus
	 * - 0x0008: accessible via DMA
	 * - 0x0010: accessible via DMA2D
	 *
	 * - 0x1FE0: reserved
	 *
	 * - 0x2000: Fast memory (Core- or Tightly-Coupled)
	 * - 0x4000: non-volatile (or battery backed) memory
	 * - 0x8000: external memory
	 */
	.table.heap : ALIGN(4)
	{
		__table_heap_start = .;
		LONG(0x001f)
		LONG(__heap1_start)
		LONG(__heap1_end)
		LONG(0x0019)
		LONG(__heap2_start)
		LONG(__heap2_end)
		LONG(0x0019)
		LONG(__heap3_start)
		LONG(__heap3_end)
		LONG(0x2002)
		LONG(__heap0_start)
		LONG(__heap0_end)
        
		__table_heap_end = .;
	} >FLASH


	. = ALIGN(4);
	__rom_end = .;


	/* DWARF debug sections */
	.debug_abbrev   0 : { *(.debug_abbrev) }
	.debug_aranges  0 : { *(.debug_aranges) }
	.debug_frame    0 : { *(.debug_frame) }
	.debug_info     0 : { *(.debug_info) }
	.debug_line     0 : { *(.debug_line) }
	.debug_loc      0 : { *(.debug_loc) }
	.debug_macinfo  0 : { *(.debug_macinfo) }
	.debug_pubnames 0 : { *(.debug_pubnames) }
	.debug_pubtypes 0 : { *(.debug_pubtypes) }
	.debug_ranges   0 : { *(.debug_ranges) }
	.debug_str      0 : { *(.debug_str) }

	.comment 0 : { *(.comment) }
	.ARM.attributes 0 : { KEEP(*(.ARM.attributes)) }
	/DISCARD/ : { *(.note.GNU-stack)  }

}
```

</details>

**Comment by salkinium** [comment]
`modm_fastdata` is not guaranteed to be DMA-able, but plain `malloc` and `new` are always allocated in DMA-able memory, and this is also true for any malloc that FreeRTOS does. The only other thing in CCM is the main stack, but it's generally bad practice to DMA memory from the stack, so it's probably not that?

(It's probably also not very fast to access the F7 DTCM via the Ethernet MAC, I would place this in normal SRAM too.)

You can use overwrite the option `:platform:heap:allocator=newlib` so that the CCM heap isn't accessible by malloc at all. That would at least rule out the heap.

**Comment by kikass13** [comment]
I am not really sure that i understand the solution (my knowledge is way to limited in this regard).
 * Is disabling the CCM a good idea?
 * > I just removed the modm_fastdata attribute as suggested, but ethernet still does not work.
      *  Why does this not work then? 
              * Is the dma now trying to now r/w in sram instead of the CCM ? 
              * And is the data buffer still located in CCM because FreeRTOS created it? (which is CCM for stack/heap by default?)?
 * how can modm ensure that dma is working correctly on different devices then?
     * is there  capability flag in modm, which lbuild can use to define whether or not something has access to specific types memory types?
 
... but thank you @jnewcomb, my last straws were "I hope there is nothing wrong wrong with the dma and/or interrupts" , but  you nailed the problem :)

**Comment by salkinium** [comment]
> Is disabling the CCM a good idea?

No, it's 64kB of single-cycle access SRAM (but only from the CPU) it would be very wasteful to ignore that.

> Why does this not work then?

I don't understand it either. Only the main stack, the fastdata and the heap0 is located in CCM. Is there something getting DMA'd from the main stack?

> how can modm ensure that dma is working correctly on different devices then?

The linkerscripts are all specifically designed so that the "normal" data sections (.bss, .noinit, .data) are in main SRAM which is always DMA-able. Same goes for the heap.
Only on devices that have a "fast" memory, like CCM on STM32F4 or TDCM on STM32F7, the data section `.fastdata` is placed there, otherwise it is also placed in main SRAM.

So there should be no surprises like this at all if you don't use any memory attributes, but
if you use *any* memory attribute like `.fastdata` it can lead to weird results, depending on the family and even on the DMA instance.

We need to document this better, since we're starting to look into DMA now more and this very annoying to debug.

> is there capability flag in modm

For the heap there are [these MemoryTraits](https://docs.modm.io/develop/api/stm32f439ziy6/group__modm__architecture__memory.html#ga4ab452f5d1300a45f045af588fc25fb2) that you can use to get memory with extra traits. But you need to specifically request it, by default only DMA-able memory is allocated.

This is also how can allocate memory on the external heap (16MB on the STM32F469 Discovery for example).

```cpp
auto *p = new (modm::MemoryFastData) Foo;
auto *q = new (modm::MemoryExternal, std::nothrow) Foo;
```

**Comment by kikass13** [comment]
Thanks for the clarification, one question (which you answered partially) 
 
> So there should be no surprises like this at all if you don't use any memory attributes, but
> if you use _any_ memory attribute like `.fastdata` it can lead to weird results, depending on the family and even on the DMA instance.

My original question was specifically targeted at  dma bus capabilities - how can one (is it plausible?) ensure (via abstraction) that an internal controller/module master has dma access to other internal device slaves?

Is it (for example) feasible to abstract the Bus matrix shown by @rleh and generate DMA capabilities on a device specific basis: 
 * Device A (stm32f7xxxxx)
    * Master1(memory mapped module for ETH PHY) > Slave1 (memory mapped module for CCM) > COOL    
 * Device B (stm32f4xxxxx)
    * Master1(memory mapped module for ETH PHY) > Slave1 (memory mapped module for CCM) > NOT COOL

so that modm (pre compilation?) warn developers that the dma capabilities they have declared can not be  properly mapped and are therefore not possible on the device they are using

**Comment by rleh** [comment]
I did some further research: Without changes to the current source code I have to force both the `.fastdata` and the `.stack` sections into RAM (currently in CCM) to get Ethernet running.

Removing the `modm_fastdata` attributed and keeping `.fastdata` section in CCM does not work. I don't understand why, because the `modm_fastdata` or `modm_section(.fastdata)` attribute are not used anywhere else (except `platform/clock/rcc.cpp`).

---

> @salkinium: [...] but it's generally bad practice to DMA memory from the stack [...]

Why?

With Ethernet (and FreeRTOS+TCP) it is probably (?) not possible to allocate all DMA-related variables/buffers statically, so we have to choose between stack and heap.
In some applications the usage of heap is not desirable (FreeRTOS config `configSUPPORT_DYNAMIC_ALLOCATION`), so stack is the only option...

**Comment by rleh** [comment]
> My original question was specifically targeted at dma bus capabilities - how can one (is it plausible?) ensure (via abstraction) that an internal controller/module master has dma access to other internal device slaves?

For dynamically allocated memory: Via memory traits as explained by @salkinium above.
Stack and static memory: I'm not aware of any solution to the problem other than not using storage like CCM at all...

We could provide a utility function in modm that displays the capability of a given memory address (pointer) at runtime, but that would only be useful in rare situations (like now 😆).

**Comment by salkinium** [comment]
> We could provide a utility function in modm 

I mean, we could have a debug assertion in the DMA driver to check the address range at runtime. The information is currently **not** part of modm-devices, but it's not difficult to add. It's probably the best quick hack that we can add.

Edit: Of course that only works if you use the DMA driver, a stand-alone attribute function is probably still better in general.

**Comment by chris-durand** [comment]
> > @salkinium: [...] but it's generally bad practice to DMA memory from the stack [...]
> 
> Why?

If you return from the function the stack memory gets deallocated. You have to make sure the DMA transfer could never continue afterwards.

**Comment by rleh** [comment]
> If you return from the function the stack memory gets deallocated. You have to make sure the DMA transfer could never continue afterwards.

Of course. But that is the same issue with (manually) freeing dynamically allocated memory...

**Comment by rleh** [comment]
I think I would consider it useful to give the modm:platform:cortex-m module an option not to create the stack in non-DMA memory, and probably even enable it by default.
(As far as I know the stack is also in SRAM by default on other toolchains (ST-Cube...)).
If you want to have the additional performance of TCM/CCM for your stack you can enable this option and should be aware of the disadvantages.

A broader use of DMA probably brings more advantages in total than having the stack in TCM/CCM.
When I look at DmaSpiMaster (which has recently become available on many more devices) it is (unfortunately) very easy to run into the same problem there unknowingly.

**Comment by salkinium** [comment]
>> @salkinium: [...] but it's generally bad practice to DMA memory from the stack [...]
>
> Why?

I was mainly thinking about modm's use of protothreads and resumable functions, where the stack doesn't really exists and is continously changed under the hood.

For FreeRTOS it's different, since the stack remains untouched IFF you wait synchronously for the DMA transfer to end. In general though, I'm not sure what guarantees C/C++ gives about stack memory lifetimes.

Regardless, only the *main stack* (which is not a FreeRTOS thread!) is allocated in the CCM, all other stacks are either dynamically allocated in heap, or statically (by modm::Thread) in main SRAM DMA-able memory. 

I am however open to changing the main stack placement, but for CCM the access speedup is >2x compared to SRAM, therefore I placed it there by default.

> Without changes to the current source code I have to force both the .fastdata and the .stack sections into RAM (currently in CCM) to get Ethernet running.

You really have to go out of your way to allocate something in fastdata, which is why this is a very confusing to me. `scons listing` will give you a map of what objects are placed in `.fastdata` etc.

**Comment by rleh** [comment]
> I mean, we could have a debug assertion in the DMA driver to check the address range at runtime.

👍🏽 


> The information is currently **not** part of modm-devices, but it's not difficult to add. It's probably the best quick hack that we can add.

Where does the information for the `MemoryTraits modm::MemoryDMA` come from?

**Comment by salkinium** [comment]
> Where does the information for the MemoryTraits modm::MemoryDMA come from?

It's shamefully hardcoded inside the linkerscripts in the heap table (in manually translated *binary* format even!!!). This needs to be extracted into modm-devices ideally.
https://github.com/modm-io/modm/blob/develop/src/modm/platform/core/stm32/linkerscript/stm32_dccm.ld.in#L59-L68

**Comment by chris-durand** [comment]
>  In general though, I'm not sure what guarantees C/C++ gives about stack memory lifetimes.

It's simple, in C++ terms objects of *automatic storage duration* (that is all local objects *not* declared as `static`, `extern` or `thread_local`) live exactly as long as the enclosing code block.

**Comment by mikewolfram** [comment]
Reading your posts about the .fast_data section reminds me, there was a comment in the original STM32 HAL implementation:
```c++
/* MAC buffers: ---------------------------------------------------------*/

/* Put the DMA descriptors in '.first_data'.
This is important for STM32F7, which has an L1 data cache.
The first 64KB of the SRAM is not cached.
See README.TXT in this folder. */

/* Ethernet Rx MA Descriptor */
__attribute__ ((aligned (32)))
#if defined(STM32F7xx)
        __attribute__ ((section(".first_data")))
#endif
        ETH_DMADescTypeDef  DMARxDscrTab[ ETH_RXBUFNB ];

#if( ipconfigZERO_COPY_RX_DRIVER == 0 )
        /* Ethernet Receive Buffer */
        __ALIGN_BEGIN uint8_t Rx_Buff[ ETH_RXBUFNB ][ ETH_RX_BUF_SIZE ] __ALIGN_END;
#endif

/* Ethernet Tx DMA Descriptor */
__attribute__ ((aligned (32)))
#if defined(STM32F7xx)
        __attribute__ ((section(".first_data")))
#endif
        ETH_DMADescTypeDef  DMATxDscrTab[ ETH_TXBUFNB ];

#if( ipconfigZERO_COPY_TX_DRIVER == 0 )
        /* Ethernet Transmit Buffer */
        __ALIGN_BEGIN uint8_t Tx_Buff[ ETH_TXBUFNB ][ ETH_TX_BUF_SIZE ] __ALIGN_END;
#endif
```
Good finding and sorry, I didn't add it to the first implementation. Since I'm on a F7 and had no access to an F4 for testing I skipped all non-F7 specific code at that time.
