### ISSUE TITLE
Outdated CI Docs

### ISSUE THREAD

**Issue by TomSaw** [modm-io/modm#617]
There's old CircleCI Docu in test/README.md. Please update instructions for new github-CI

```
!!! tip "Add your example to our CI"
	If you created a new folder inside `modm/examples`, you need to add it to
	one of the jobs in `.circleci/config.yml`:
	```sh
	- run:
	  name: Examples YOUR TARGET
	  command: |
	    (cd examples && ../tools/scripts/examples_compile.py new_folder)
	```

```

**Comment by rleh** [comment]
```diff
+one of the jobs in `.github/workflows/linux.yml`:
-one of the jobs in `.circleci/config.yml`:
```

I think that it...

**Comment by rleh** [comment]
@TomSaw Do you want to fix that yourself (one additional commit in one of you open pull requests)?

**Comment by TomSaw** [comment]
Oh... thought it's more complicated.
Never touched any CI before. If it's just 3 lines, i prefer to leave it to someone who already knows anything.
Got enough construction sites for now.

**Comment by rleh** [comment]
Is `test/README.md` visible on https://modm.io/? (If yes: where?) @salkinium 

Otherwise we (someone™️) should rewrite the MkDocs syntax  (e.g. `!!! tip`) to something that looks nice in Githubs Markdown (currently it looks a bit ugly: https://github.com/modm-io/modm/blob/develop/test/README.md)

**Comment by salkinium** [comment]
Whoops. I forgot about rewriting this when I adapted the homepage guides. I'll rewrite it when I have time.
