### ISSUE TITLE
Stream formatting - hex values prefixed 

### ISSUE THREAD

**Issue by jnewcomb** [modm-io/modm#630]
Hi folks..
Try as I might - I'm unable to get the logger to print a 32bit HEX..
I've run out of ideas on the code.. any hints as to where to look next? (another career maybe!)

Based on the STM32F429 blink example, GCC 10.2.1

````
auto crc_val1 = UINT32_C(32768);
MODM_LOG_DEBUG << "# crc_val1: " << crc_val1 << modm::endl;
MODM_LOG_DEBUG << "# crc_val1: " << std::hex << crc_val1 << modm::endl;

auto crc_val2 = INT32_C(32769);
MODM_LOG_DEBUG << "# crc_val2: " << crc_val2 << modm::endl;
MODM_LOG_DEBUG << "# crc_val2: " << std::hex << crc_val2 << modm::endl;

uint32_t crc_val3 = UINT32_C(32770);
MODM_LOG_DEBUG << "# crc_val3: "  << crc_val3 << modm::endl;
MODM_LOG_DEBUG << "# crc_val3: " << std::hex << crc_val3 << modm::endl;

uint32_t crc_val4 = UINT32_C(32771);
MODM_LOG_DEBUG << "# crc_val4: "  << crc_val4 << modm::endl;
MODM_LOG_DEBUG << "# crc_val4: " << std::hex << crc_val4 << modm::endl;

uint32_t crc_val5 = UINT32_C(32772);
MODM_LOG_DEBUG << "# crc_val5: "  << static_cast<uint32_t>(crc_val5) << modm::endl;
MODM_LOG_DEBUG << "# crc_val5: " << std::hex << static_cast<uint32_t>(crc_val5) << modm::endl;

uint64_t crc_val6 = UINT32_C(32773);
MODM_LOG_DEBUG << "# crc_val6: "  << crc_val6 << modm::endl;
MODM_LOG_DEBUG << "# crc_val6: " << std::hex << crc_val6 << modm::endl;

MODM_LOG_DEBUG << "# CRC OK: " << UINT32_C(0xABCDEF) << modm::endl;
MODM_LOG_DEBUG << "# CRC OK: " << std::hex << UINT32_C(0xABCDEF) << modm::endl;

MODM_LOG_DEBUG << "# CRC OK: " << static_cast<uint32_t>(UINT32_C(0xABCDEF)) << modm::endl;
MODM_LOG_DEBUG << "# CRC OK: " << std::hex << static_cast<uint32_t>(UINT32_C(0xABCDEF)) << modm::endl;


MODM_LOG_DEBUG << "# CRC OK: " << std::hex << 123 << modm::endl;
MODM_LOG_DEBUG << "# CRC OK: " <<  123 << modm::endl;

MODM_LOG_DEBUG << "# CRC OK: " << 1.23 << modm::endl;
````
gives:

````
# crc_val1: 32768
# crc_val1: 0x10000B2832768
# crc_val2: 32769
# crc_val2: 0x10000B2832769
# crc_val3: 32770
# crc_val3: 0x10000B2832770
# crc_val4: 32771
# crc_val4: 0x10000B2832771
# crc_val5: 32772
# crc_val5: 0x10000B2832772
# crc_val6: 32773
# crc_val6: 0x10000B2832773
# CRC OK: 11259375
# CRC OK: 0x10000B2811259375
# CRC OK: 11259375
# CRC OK: 0x10000B2811259375
# CRC OK: 0x10000B28123
# CRC OK: 123
# CRC OK: 1.23000e+00
````

Takes me here iostream.hpp (line 191) - It seems to think it's a function pointer..
````
	/// Write the hex value of any function pointer
	template<class Ret, class... Args>
	IOStream&
	operator << (Ret(*pointer)(Args...))
	{ writePointer(reinterpret_cast<const void*>(&pointer)); return *this; }
````

Maybe linked to this compile error message..
Error    format '%X' expects argument of type 'unsigned int', but argument 3 has type 'long unsigned int' 

![image](https://user-images.githubusercontent.com/2300200/118136831-73bf9d00-b3fc-11eb-9d5f-ba29530b5845.png)

UPDATE - Fixed: this works. Without the cast, I can't compile. I wish I could explain the reason but I have to avoid uint32_t with streams.. curious.
![image](https://user-images.githubusercontent.com/2300200/118145108-23007200-b405-11eb-8557-4f59a18ec8aa.png)

Why is it the more I learn, the dumber I feel!

**Comment by salkinium** [comment]
You need to use `modm::hex`, I'm not even sure what `std::hex` actually does internally… 😬 Here it seems to be printing the pointer of the `std::hex` function then the decimal value of the `uint32_t`. 

Unfortunately `modm::IOStream` is not compatible with any of the `std::iostream` stuff, mainly because on AVRs there is/was no such thing. It's also quite large and comes with a lot of encoding baggage that makes it a pain to port.

**Comment by salkinium** [comment]
> Error format '%X' expects argument of type 'unsigned int', but argument 3 has type 'long unsigned int'

`unsigned int` and `long unsigned int` are separate types, that are both 32-bit unsigned integers (on Cortex-M). The printf specification wants an `unsigned int` for `%X`, however `uint32_t` is aliased to `long unsigned int`, so you need to use `%lX`.

<img width="673" src="https://user-images.githubusercontent.com/163066/118205727-4a852800-b461-11eb-93b4-f65cb9ce7de5.png">

Also the width of `unsigned int` vs `unsigned long` differs between systems, see [these  workarounds in IOStream](https://github.com/modm-io/modm/blob/develop/src/modm/io/iostream.hpp.in#L152-L184).

The "proper" solution is [to use `<inttypes.h>`](https://www.cplusplus.com/reference/cinttypes/), in this case `PRIX32` which expands to the right printf identifier for `uint32_t` in hex:
<img width="1409"  src="https://user-images.githubusercontent.com/163066/118207070-2414bc00-b464-11eb-98d9-f4ce72f5ec6b.png">


 Alternatively you *may* be able to ignore the printf compile error by adding this to the `project.xml` compile flag collectors:

```xml
<collectors>
  <collect name="modm:build:ccflags">-Wno-error=format</collect>
</collectors>
```

> any hints as to where to look next? (another career maybe!)

I feel you! I'm just more terrible at everything else.

> Why is it the more I learn, the dumber I feel!

It's not you, it's the standards body that has for many decades ignored how embedded systems work in practice and now you cannot change it anymore. Short of changing to Rust there's nothing that can be done. At least in recent years embedded has taken a more dominant role in the C++ standards body, but it's a little late now…

**Comment by jnewcomb** [comment]
Well.. `modm::hex` and ` "%lX"` fixed that one!  The joys of starting a new codebase.
Thanks for clearing up my confusion regarding the use of int types, all makes sense now!
