### ISSUE TITLE
[stm32] Advanced control timer driver resets TIMx_RCR "for some unknown reason"

### ISSUE THREAD

**Issue by chris-durand** [modm-io/modm#794]
Configuring the output compare mode [sets the `TIMx_RCR` register](https://github.com/modm-io/modm/blob/c0a8c51e4a1ef536d24793e461d06d23f2d2b9e2/src/modm/platform/timer/stm32/advanced.cpp.in#L202) "for some unknown reason":
```
// Disable Repetition Counter (FIXME has to be done here for some unknown reason)
TIM{{ id }}->RCR = 0;
```

Does anyone know why this line this might be there? It was part of the first commit adding the driver by @dergraaf in 2011.
It cost me some hours of debugging my code which sets the register to 1. I would like to remove this. Any thoughts?

@rleh @salkinium

**Comment by salkinium** [comment]
> I would like to remove this.

I think I also stumbled over this some time ago, I then used raw register access. Feel free to remove it. I don't think the removal breaks anything.
