### ISSUE TITLE
STM32G4 ADC internal channel mapping wrong

### ISSUE THREAD

**Issue by chris-durand** [modm-io/modm#802]
From the G4 reference manual for ADC1:
![g4_adc](https://user-images.githubusercontent.com/25187160/147887717-46d35f92-1d76-471a-a0d8-ce387dccf017.png)

Our code has:
```enum class Channel : uint8_t
{
    Channel1 = 1,
    […]
    Temperature = 17,
    BatDiv3     = 18,
};
```

I'll fix it. It would be so much easier if we had machine readable data for this.

**Comment by rleh** [comment]
There is the (very) old unmerged #324 that at least partially fixes the issue.
