### ISSUE TITLE
Executing lbuild build after 8708f3dc

### ISSUE THREAD

**Issue by se-bi** [modm-io/modm#83]
I am facing some trouble with the latest changes introduced by 8708f3dc,
when executing `lbuild build`.

That occurs with various modm examples.

Is it a Python3.5/3.6 issue?

```
  File "/home/user/.local/lib/python3.5/site-packages/lbuild/parser.py", line 110, in parse_repository
    repo = repository.Repository.parse_repository(repofilename)
  File "/home/user/.local/lib/python3.5/site-packages/lbuild/repository.py", line 64, in parse_repository
    repo._functions['init'](RepositoryInitFacade(repo))
  File "[..]/modm/repo.lb", line 164, in init
    name = re.search("<module>(modm:board:.*?)</module>", config.read_text())[1].replace("modm:", "")
TypeError: '_sre.SRE_Match' object is not subscriptable
```

**Comment by salkinium** [comment]
This searches through all the board `board.xml` files to extract the name of the board module. Do you have any custom boards there? Can you add a `print(config)` before this line?

**Comment by salkinium** [comment]
Ah, no, this is a Python 3.5 issue, where I should use `.group(1)` instead of `[1]`. Ooops.

**Comment by salkinium** [comment]
If this fixes it, do you want to open a quick PR?

**Comment by se-bi** [comment]
> Ah, no, this is a Python 3.5 issue, where I should use `.group(1)` instead of `[1]`. Ooops.

Yep, works for me ;-)

> If this fixes it, do you want to open a quick PR?

Coming soon.
