### ISSUE TITLE
Disabling PLL on STM32

### ISSUE THREAD

**Issue by ser-plu** [modm-io/modm#943]
If I need to change PLL settings (i need it when switching from a bootloader to the main application), I need to change system clock to Internal source and to disable PLL. There is a function for the first part, but the second required something like this:

```c++
bool
Rcc::disablePll(uint32_t waitCycles) {
	RCC->CR &= RCC_CR_PLLON;
	while (RCC->CR & RCC_CR_PLLRDY) and --waitCycles)
		;
}
```

**Comment by chris-durand** [comment]
@ser-plu Could you check if the branch from #944 works for you?
