### ISSUE TITLE
[stm32] Interrupt handler indirection causes unnecessary latency

### ISSUE THREAD

**Issue by strongly-typed** [modm-io/modm#963]
`MODM_ISR(DMA1_Channel{{N}})` calls nothing but `Dma1::Channel<DmaBase::Channel::Channel{{N}}>::interruptHandler();` in [`dma.cpp.in`](https://github.com/modm-io/modm/blob/develop/src/modm/platform/dma/stm32/dma.cpp.in#L18)

Unfortunately, these calls are not inlined. Adding an `inline` did not change anything for me. These calls are real calls, increasing interrupt latency unnecessarily.

[InterruptHandler](https://github.com/modm-io/modm/blob/develop/src/modm/platform/dma/stm32/dma.hpp.in#L311) is a jinja-generated C++ template ...

Why not jinja-generate this code directly into `dma.cpp` without the C++ template?

(Yes, I have to shave off some nanoseconds IRQ latency and I try to stay with modm for convenience.)

**Comment by chris-durand** [comment]
You could try adding `[[gnu::always_inline]]` at the definition of `interruptHandler()`. That should force inlining.
