### ISSUE TITLE
Update Website Installation Guide

### ISSUE THREAD

**Issue by se-bi** [modm-io/modm#996]
(Not sure where the website description is...)

I guess the link to the pre-built ARM toolchain is outdated.
The following saves one click :tada: , where I usually scroll over:
https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/downloads

or the URL where that actually forwards to as well :sweat_smile: :
https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads

**Comment by rleh** [comment]
Already fixed in #972

**Comment by se-bi** [comment]
:+1: Alright, you also switch the "vendor"
